# @package _group_
name: gym_extensions-halfcheetah_gravity-mt5
num_envs: 5
benchmark_name: halfcheetah_gravity.MT5
random_goal: True
description:
  HalfCheetah-v2: HalfCheetah-v2 env
  HalfCheetahGravityHalf-v0: HalfCheetah-v2 env with half gravity.
  HalfCheetahGravityThreeQuarters-v0: HalfCheetah-v2 env with three quarters gravity.
  HalfCheetahGravityOneAndHalf-v0: HalfCheetah-v2 env with one and half gravity.
  HalfCheetahGravityOneAndQuarter-v0: HalfCheetah-v2 env with one and quarter gravity.
ordered_task_list: # will be auto-populated.
wrappers:
  scale_reward_wrapper:
    reward_scale: 0.1
  max_step_success_wrapper:
    max_step: 1000
network:
  hidden_dim: 400
  num_layers: 2
  paco_hidden_features: 400
  paco_num_of_param_set: 3
  paco_num_layers: 2
  sm_hidden_features: 400
  sm_hidden_layers: 1
  sm_emb_hidden_layers: 1
  sm_num_layers: 4
  sm_num_modules: 4
  sm_module_hidden_features: 64
  sm_gating_hidden_features: 128