# @package _group_
name: gym_extensions-halfcheetah_body-mt8
num_envs: 8
benchmark_name: halfcheetah_body.MT8
random_goal: True
description:
  HalfCheetahBigTorso-v0: HalfCheetah-v2 env with big torso.
  HalfCheetahSmallTorso-v0: HalfCheetah-v2 env with small torso.
  HalfCheetahBigThigh-v0: HalfCheetah-v2 env with big thigh.
  HalfCheetahSmallThigh-v0: HalfCheetah-v2 env with small thigh.
  HalfCheetahBigLeg-v0: HalfCheetah-v2 env with big leg.
  HalfCheetahSmallLeg-v0: HalfCheetah-v2 env with small leg.
  HalfCheetahBigFoot-v0: HalfCheetah-v2 env with big foot.
  HalfCheetahSmallFoot-v0: HalfCheetah-v2 env with small foot.
ordered_task_list: # will be auto-populated.
wrappers:
  scale_reward_wrapper:
    reward_scale: 0.1
  max_step_success_wrapper:
    max_step: 1000
network:
  hidden_dim: 400
  num_layers: 2
  paco_hidden_features: 400
  paco_num_of_param_set: 3
  paco_num_layers: 2
  sm_hidden_features: 400
  sm_hidden_layers: 1
  sm_emb_hidden_layers: 1
  sm_num_layers: 4
  sm_num_modules: 4
  sm_module_hidden_features: 64
  sm_gating_hidden_features: 128