# @package _group_
name: metaworld-mt50
num_envs: 50
benchmark:
  _target_: metaworld.MT50
random_goal: True
dummy:
  _target_: metaworld.MT1
  env_name: pick-place-v2
description:
  reach-v2: Reach a goal position. Randomize the goal positions.
  push-v2: Push the puck to a goal. Randomize puck and goal positions.
  pick-place-v2: Pick and place a puck to a goal. Randomize puck and goal positions.
  door-open-v2: Open a door with a revolving joint. Randomize door positions.
  drawer-open-v2: Open a drawer. Randomize drawer positions.
  drawer-close-v2: Push and close a drawer. Randomize the drawer positions.
  button-press-topdown-v2: Press a button from the top. Randomize button positions.
  peg-insert-side-v2: Insert a peg sideways. Randomize peg and goal positions.
  window-open-v2: Push and open a window. Randomize window positions.
  window-close-v2: Push and close a window. Randomize window positions.
  door-close-v2: Close a door with a revolvinig joint. Randomize door positions.
  reach-wall-v2: Bypass a wall and reach a goal. Randomize goal positions.
  pick-place-wall-v2: Pick a puck, bypass a wall and place the puck. Randomize puck and goal positions.
  push-wall-v2: Bypass a wall and push a puck to a goal. Randomize puck and goal positions.
  button-press-v2: Press a button. Randomize button positions.
  button-press-topdown-wall-v2: Bypass a wall and press a button from the top. Randomize button positions.
  button-press-wall-v2: Bypass a wall and press a button. Randomize the button positions.
  peg-unplug-side-v2: Unplug a peg sideways. Randomize peg positions.
  disassemble-v2: Pick a nut out of the a peg. Randomize the nut positions.
  hammer-v2: Hammer a screw on the wall. Randomize the hammer and the screw positions.
  plate-slide-v2: Get a plate from the cabinet. Randomize plate and cabinet positions
  plate-slide-side-v2: Get a plate from the cabinet sideways. Randomize plate and cabinet positions
  plate-slide-back-v2: Slide a plate into a cabinet. Randomize the plate and cabinet positions
  plate-slide-back-side-v2: Slide a plate into a cabinet sideways. Randomize the plate and cabinet positions
  handle-press-v2: Press a handle down. Randomize the handle positions
  handle-pull-v2: Pull a handle up. Randomize the handle positions.
  handle-press-side-v2: Press a handle down sideways. Randomize the handle positions.
  handle-pull-side-v2: Pull a handle up sideways. Randomize the handle positions.
  stick-push-v2: Grasp a stick and push a box using the stick. Randomize stick positions.
  stick-pull-v2: Grasp a stick and pull a box with the stick. Randomize stick positions.
  basketball-v2: Dunk the basketball into the basket. Randomize basketball and basket positions.
  soccer-v2: Kick a soccer into the goal. Randomize the soccer and goal positions.
  faucet-open-v2: Rotate the faucet counter-clockwise. Randomize faucet positions.
  faucet-close-v2: Rotate the faucet clockwise. Randomize faucet positions.
  coffee-push-v2: Push a mug under a coffee machine. Randomize the mug and the machine positions.
  coffee-pull-v2: Pull a mug from a coffee machine. Randomize the mug and the machine positions.
  coffee-button-v2: Push a button on the coffee machine. Randomize the position of the coffee machine.
  sweep-v2: Sweep a puck off the table. Randomize puck positions.
  sweep-into-v2: Sweep a puck into a hole. Randomize puck positions.
  pick-out-of-hole-v2: Pick up a puck from a hole. Randomize puck and goal positions.
  assembly-v2: Pick up a nut and place it onto a peg. Randomize nut and peg positions.
  shelf-place-v2: Pick and place a puck onto a shelf. Randomize puck and shelf positions.
  push-back-v2: Pull a puck to a goal. Randomize puck and goal positions.
  lever-pull-v2: Pull a lever down 90 degrees. Randomize lever positions.
  dial-turn-v2: Rotate a dial 180 degrees. Randomize dial positions.
  bin-picking-v2: Grasp the puck from one bin and place it into another bin. Randomize puck positions.
  box-close-v2: Grasp the cover and close the box with it. Randomize the cover and box positions.
  hand-insert-v2: Insert the gripper into a hole.
  door-lock-v2: Lock the door by rotating the lock clockwise. Randomize door positions.
  door-unlock-v2: Unlock the door by rotating the lock counter-clockwise. Randomize door positions.
ordered_task_list: # will be auto-populated.
wrappers:
  scale_reward_wrapper:
    reward_scale: 0.1
  max_step_wrapper:
    max_step: 200
network:
  hidden_dim: 400
  num_layers: 5
  paco_hidden_features: 400
  paco_num_of_param_set: 5
  paco_num_layers: 3
  sm_hidden_features: 400
  sm_hidden_layers: 2
  sm_emb_hidden_layers: 1
  sm_num_layers: 4
  sm_num_modules: 4
  sm_module_hidden_features: 128
  sm_gating_hidden_features: 256